canonical/kubeflow-dashboard-operator

.github/workflows/integrate.yaml
.github/workflows/on_pull_request.yaml
.github/workflows/on_push.yaml
.github/workflows/publish.yaml
.github/workflows/release.yaml
.github/workflows/weekly_ci.yaml
src/charm.py
test-requirements.txt

Charming actions updated according to the ones agreed on template-operator and dex-auth charms.
The aim was to:
- add release charm action
- have two publish actions for `on: push` and `on: pull_request`:
- on pull_request, publish to branch no matter if tests passed (tests and publish should run simultaneously)
- on push, publish to latest/edge only if tests passed
- avoid re-running the tests on pull_request
- use reusable workflows in order to avoid duplication of code.
Note: this is a single-charm repo with one resource.

Add charming actions

---

.github/workflows/integrate.yaml
.gitignore
charmcraft.yaml
metadata.yaml
tests/integration/test_charm.py

- Updated the upstream image version to 1.5.0
- Updated charmcraft python packages to use versions other than `setuptools 62.2.0` and `pip 22.1`
- Updated the CI to test on microk8s 1.22
---
Tests:
1. Deploy full bundle on microk8s 1.21 (both rbac disabled and enabled) with updated kubeflow-profiles and kubeflow-dashboard v1.5 - OK
- all charms are active
- access and login to dashboard - OK
2. Deploy kubeflow-profiles and kubeflow-dashboard on microk8s v1.22 - OK
Note: if kubeflow-dashboard is deployed on microk8s v1.22, it requires kubeflow-profiles 1.5 (`latest/edge`) since `latest/stable` uses CRDs that aren't supported in k8s v1.22.
3. Integration and unit tests (run on microk8s 1.21 and 1.22) - OK

Support k8s v1.22+ with kubeflow 1.5

---

tests/integration/test_charm.py

This fixes the integration tests for `pytest-asyncio` `v0.19.0`, as described [here](https://github.com/canonical/kubeflow-dashboard-operator/pull/34#discussion_r938242618) and [here](https://github.com/canonical/bundle-kubeflow/issues/470)

fix: use pytest_asyncio.fixture so tests work w/asyncio-mode=strict

---

config.yaml
lib/charms/observability_libs/v1/kubernetes_service_patch.py
src/charm.py
src/templates/profile_crds.yaml.j2
tests/unit/test_operator.py

Besides removing the admin profile from the charm, this PR also adds refactoring already approved in #38 (its in different branch right now but we may need it sooner)
**Important**: I deployed the latest/edge bundle and run the examples in https://charmed-kubeflow.io/docs/kubeflow-basics I think we don't need the default admin profile (which is user profile with admin name). On every first time login (e.g. user123) the dashboard directly creates a user with the same profile.

feat: remove admin profile

---

CODEOWNERS
metadata.yaml

Backporting 
[[skip ci] git-xargs programmatic commit](https://github.com/canonical/kubeflow-dashboard-operator/commit/445184e204797ad42c234f33f0c2ff5829e71821)
[chore: Bump image versions](https://github.com/canonical/kubeflow-dashboard-operator/commit/50cf6436f432b225b0e95b1ebb88b3118d521be0)

[cherry-pick] 44518e and 50cf643

---

lib/charms/kubeflow_dashboard/v0/kubeflow_dashboard_sidebar.py

Use charmcraft library for adding items to the sidebar menu. Installation and setup steps are in the library documentation (beginning of the file). 
Related PRs:
- [volumes](https://github.com/canonical/kubeflow-volumes-operator/pull/38)
- [kfp](https://github.com/canonical/kfp-operators/pull/102)
- [notebook](https://github.com/canonical/notebook-operators/pull/48)
- [tensorboard](https://github.com/canonical/kubeflow-tensorboards-operator/pull/16)
- [katib](https://github.com/canonical/katib-operators/pull/29)

feat: add library for sidebar relation handling

---

.github/workflows/integrate.yaml

This is a temporary fix to address [this bug](https://bugs.launchpad.net/juju/+bug/1992833), which raises errors about the series of the charm being deployed.

fix: pin juju agent version to 2.9.34 github runners to ubuntu-20.04

---

src/charm.py
tests/unit/test_operator.py

A BlockedStatus mean a human has to manually intervene to ublock the unit and let it proceed. There were some conditions where no external intervention could ublock the unit. Adding appropriate logging and exceptions to catch errors and set status correctly.
Fixes canonical/bundle-kubeflow#549
Merge after #110, CI error should be fixed after that.

fix: remove BlockedStatus statements in charm code

---

src/charm.py
tests/integration/test_charm.py
tests/unit/test_operator.py

This change puts the charm into Blocked status when the profile relation is missing, but to Waiting when the relation exists but does not have data in it (presumably because we're just waiting on the profile charm to reply).
closes #97

fix: put charm to Blocked status when missing relation to profiles

---

lib/charms/kubeflow_dashboard/v0/kubeflow_dashboard_links.py
tests/unit/test_sidebar_lib.py

The `DashboardLink.location` field accepts only specific values.  This PR adds validation to assert that during runtime.  
Closes #131

Add validation on `DashboardLink.location`

---

charmcraft.yaml

Remove reference to the `files` directory that doesn't exist anymore from the charmcraft.yaml file.
Closes #149

fix: Drop stale directory ref from charmcraft.yaml

---

metadata.yaml
src/charm.py
src/templates/auth_manifests.yaml.j2
tests/integration/test_charm.py

- Bump image version to v1.8.0-rc.0 in preparation for the 1.8 release based on kubeflow/manifests repo tag v1.8.0-rc.0.
- Remove unused `profiles` resource from Auth manifests, this resource was needed for creating the `admin` profile, which is no longer applicable.
- Set the newly added `POD_NAMESPACE` env var, for context see the issue https://github.com/canonical/bundle-kubeflow/issues/698

feat: update charm 1.8.0-rc.0

---

metadata.yaml
src/charm.py

Use the CKF owned image for the charm instead of upstream's.
Fixes #164

chore: use charmedkubeflow/kubeflow-central-dashboard as oci-image

---

.gitignore
lib/charms/grafana_k8s/v0/grafana_dashboard.py
metadata.yaml
src/charm.py
src/grafana_dashboards/generic.json.tmpl

The implementation was modified from what was specced. I can update the spec once the review gives a +1 too. Details for the final dashboard are in https://github.com/canonical/bundle-kubeflow/issues/877#issuecomment-2072060824.
* Implement a generic grafana dashboard that shows the state (up or down)
of all CKF charms that provide metrics.
* Fetch grafana dashboard library and implement a GrafanaDashboardProvider.
Closes canonical/bundle-kubeflow#877
This is how the dashboard looks like:
If you 'd like to test the COS integration and see the dashboard yourself, then follow the [CKF - COS integration guide](https://charmed-kubeflow.io/docs/integrate-with-cos).

feat: Add generic `Kubeflow Application Workloads State` grafana dashboard 

---

metadata.yaml
src/charm.py

This reverts commit 2811dcbfd649f1eae1b1d1468a85df63b51c2816.
This is a temporal workaround to help avoid #188. This change must be reverted again once the fix for it is available. Please note the fix depends on a newer version of juju.

Revert "chore: use charmedkubeflow/kubeflow-central-dashboard as oci-image (#178)"

---

.gitignore
lib/charms/grafana_k8s/v0/grafana_dashboard.py
metadata.yaml
src/charm.py
src/grafana_dashboards/generic.json.tmpl

* Implement a generic grafana dashboard that shows the state (up or down) of all Kubeflow applications workloads that provide metrics.
* Fetch grafana dashboard library and implement a GrafanaDashboardProvider.
This is a backport from #186.
Ref canonical/bundle-kubeflow#877

backport(feat): Add generic `Kubeflow Application Workloads State` grafana dashboard from #186

---

lib/charms/loki_k8s/v1/loki_push_api.py
metadata.yaml
requirements-integration.in
requirements-integration.txt
requirements-unit.txt
requirements.in
requirements.txt
src/charm.py
tests/integration/test_charm.py
tests/unit/test_operator.py

Added logging relation and cos integration tests from chisme.
Fixing usage of boolean in pebble layer, this cause that `if current_layer.services != new_layer.services:` condition was always true. The `'REGISTRATION_FLOW': True` was `'REGISTRATION_FLOW': 'true'`.
fixes: #195
How I tested it:
from terminal
```bash
$ tox -e integration -- --model kubeflow --keep-models
$ juju switch kubeflow
$ juju consume u1-k8s:cos.loki-logging
Added u1-k8s:admin/cos.loki-logging as loki-logging
$ juju integrate loki-logging grafana-agent-k8s
$ kubectl get services -n kubeflow | grep 8082                                                                            
kubeflow-dashboard                              ClusterIP   10.152.183.45    <none>        8082/TCP            8m13s  
$ kubectl logs -n …
```

Add logging relation kubeflow-dashboard

---

config.yaml
metadata.yaml
src/charm.py

Related to: https://github.com/canonical/kubeflow-dashboard-operator/issues/190
Compared tags `v1.8.0` and `v1.9.0-rc.0` for files `https://github.com/kubeflow/kubeflow/tree/master/components/centraldashboard/manifests/overlays/kserve`
[Some of the links in the configmap ](https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/manifests/base/configmap.yaml#L7)changed upstream. This PR resolves the changes related to this charm.
Changes:
- changing the order of some quick links related to upstream change

Update links and image for 1.9.0

---

charmcraft.yaml

Closes: https://github.com/canonical/kubeflow-dashboard-operator/issues/217
Added build-packages to fix the build process.

Fix Rust compiler

---

config.yaml

Closes: https://github.com/canonical/kubeflow-dashboard-operator/issues/214
Ordered links according to upstream ordering (except the nesting feature). 
I have tested the setting with latest/beta.
Screenshot of final ordering: 
Upstream ordering: 
Please first merge this PR to fix blocking issue: https://github.com/canonical/kubeflow-dashboard-operator/pull/218

Order dashboard menu links

---

lib/charms/kubeflow_dashboard/v0/kubeflow_dashboard_links.py
tests/unit/test_sidebar_lib.py

part of fixing #213 
Modifies the `KubeflowDashboardLinks` Library to have the requirer observe the `upgrade_charm` event so that the relation data gets updated in the event of charm upgrade
Note: the library patch is not published yet, I will publish it once the PR is approved and before merging it.
1. deploy CKF 1.8/stable
2. pick one of the charms on the requirer side of `dashboard-links` relation for which we know the links have change from 1.8 to 1.9 for example `kfp-ui`
3. clone the repo of `kfp-ui` charm (stay on `main` branch) and edit the `kubeflow_dashboard_links.py` under `lib/charms` to have the changes done in this PR.
4. pack the `kfp-ui` charm
5. refresh the deployed charm to the packed one with `juju refresh`
6. access the dashboard to check the new links are there OR view …

fix: observe `upgrade_charm` event in `KubeflowDashboardLinksRequirer`

---

metadata.yaml

Closes: https://github.com/canonical/kubeflow-dashboard-operator/issues/215
I have compared tags `v1.9.0` and `v1.9.0-rc.1` for this files https://github.com/kubeflow/manifests/tree/v1.9.0?tab=readme-ov-file#central-dashboard

chore: update images for kf 1.9.0

---

src/charm.py

Closes [issue 104 on the kubeflow-rocks repo](https://github.com/canonical/kubeflow-rocks/issues/104) along with [this PR](https://github.com/canonical/kubeflow-rocks/pull/120).
This PR changes the override strategy from `replace` to `merge`. This way, we do not need to set the `working-dir` value that is needed when integrating with the `centraldashboard` rock.

Change override to 'merge' to correctly propagate values from the centraldashboard rock

---

requirements-unit.txt
requirements.txt

This PR is a backport that fixes [this issue](https://github.com/canonical/bundle-kubeflow/issues/883).
It bumps the version of `jinja2` that is specified in the `requirements.txt` file.

backport: Bump jinja2 3.1.x -> 3.1.4

---

src/charm.py

This PR is a backport of #221, and along with [this PR](https://github.com/canonical/kubeflow-rocks/pull/121) fix [this issue](https://github.com/canonical/kubeflow-rocks/issues/104) on the kubeflow-rocks repo.

Backport: Change override to 'merge' to correctly propagate values from the centraldashboard rock

---

src/charm.py

Enables supporting cross-model ingresses.  The ingress relation supports an optional namespace parameter.  If not passed, istio-pilot uses its own namespace, which is invalid if istio and dashboard are deployed in different namespaces.

add namespace to the ingress relation data

---

metadata.yaml
src/charm.py

This commit changes the oci-image from the team's maintained rock to upstream's latest centraldashboard container image (v1.10.0-rc.0). It also changes the workload service to use tini as per indicated in the code comments.
These changes are based on the latest sync of the `kubeflow/kubeflow` to the `kubeflow/manifests` repository. See https://github.com/kubeflow/manifests/pull/2995 for reference.

chore: update centraldashboard 1.9.0 -> 1.10.0-rc.0

---

metadata.yaml

Based on the upstream 1.10 updates [PR](https://github.com/kubeflow/kubeflow/commit/90e987bf87d3e7c900926310b00bfa16b59e41eb) and manifests update [PR](https://github.com/kubeflow/manifests/pull/3071). There have been no updates to the manifests in dashboard. This PR bumps the rock to v1.10.0.
Closes https://warthogs.atlassian.net/browse/KF-7146

chore: update rock and manifests to 1.10.0 version

---

.github/workflows/integrate.yaml
tests/integration/test_charm.py

Remove the assertion that tests the kubeflow-dashboard-operator goes to Blocked when the relation with kubeflow-profiles is not there. This assertion is already covered in unit tests, and it is only adding noise at deployment time.
~~This commit ensures the dependencies like charms and relations are deployed on time which will give time for everything to be set up before moving ahead with other test cases.~~

tests: refactor build and deploy test case

---

terraform/outputs.tf

Include `metrics-endpoint` in the Terraform module's output.
Fix #272

fix: include metrics-endpoint in Terraform module outputs

---

.github/workflows/release.yaml

Introduce base-channel input in promote workflow. From main, this always run using 20.04 (see [input](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/17320449248/job/49172342285#step:3:8) and [result](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/17320449248/job/49172342285#step:3:725)). From this branch, the charm was properly updated for base 24.04 (see [input](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/17320766258/job/49173375541#step:3:7) and [result](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/17320766258/job/49173375541#step:3:725)).

fix(ci): Introduce base-channel input in promote workflow

---

terraform/README.md
terraform/main.tf
terraform/variables.tf

Updates the default base in the terraform module to 24.04 now that the
charm with 24.04 base is released to stable (done in this [action](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/17320449248)).
This is needed to fix canonical/bundle-kubeflow#1259, so by default, the
charm uses image from canonical/kubeflow-rocks#247.

terraform: change default base to 24.04

---

.github/workflows/integrate.yaml
.github/workflows/release.yaml
concierge.yaml

Ref: https://github.com/canonical/bundle-kubeflow/issues/1334
This PR backports the update to use Canonical K8s in our integration tests. Note that we also backport a fix to use `24.04` as base in the `release-charm` action.

(backport): Update CI to use Canonical K8s

---

.github/workflows/integrate.yaml

Ref: https://github.com/canonical/bundle-kubeflow/issues/1341
This PR backports a change to only run the `dump-charm-debug-artifacts` action on failure in order to save time.

fix: Change dump-charm-debug-artifacts on failure
